-
  branches:
    only:
      - master
  
  image: Visual Studio 2022
  version: 0.10.{build}
  configuration: Release

  install:
    - cmd: git submodule update --init
  
  before_build:
    - cmd: nuget restore

  build:
    project: OldRod.sln
    verbosity: minimal

  artifacts:
    - path: src/OldRod/bin/Release

